# -*- coding: utf-8 -*-
"""CS210_PROJECT_BETULGUREL_22509.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1euD9I3PWZjDS16N6LCV3YLByiLOlikIe
"""

import pandas as pd
import numpy as np
from scipy.stats import ttest_rel, pearsonr


file_path = 'DATASET.xlsx'
df = pd.read_excel(file_path, sheet_name='Sayfa1')

grade_mapping = {
    'A+': 100,
    'A ': 90,
    'A-': 85,
    'B+': 80,
    'B': 75,
    'B-': 70,
    'C+': 65,
    'C': 60,
    'C-': 55,
    'D+': 50,
    'D ': 45,
    'D-': 40,
    'F': 39
}


df['LETTER GRADE'] = df['LETTER GRADE'].map(grade_mapping)

print(df, sep='\n')

fall21_22 = df[df['TERM'] == 'FALL21-22']
spring21_22 = df[df['TERM'] == 'SPRING21-22']
fall22_23 = df[df['TERM'] == 'FALL22-23']
spring22_23 = df[df['TERM'] == 'SPRING22-23']

# Calculate the average for each term
average_fall21_22 = fall21_22['LETTER GRADE'].mean()
average_spring21_22 = spring21_22['LETTER GRADE'].mean()
average_fall22_23 = fall22_23['LETTER GRADE'].mean()
average_spring22_23 = spring22_23['LETTER GRADE'].mean()

averages = [average_fall21_22, average_spring21_22, average_fall22_23, average_spring22_23]

for i, avg in enumerate(averages, start=1):
    print(f"Semester {i} Average: {avg}")

#t-test and p-value for terms
result_fall_fall, p_value_fall_fall = ttest_ind(fall21_22['LETTER GRADE'], fall22_23['LETTER GRADE'])

result_spring_spring, p_value_spring_spring = ttest_ind(spring21_22['LETTER GRADE'], spring22_23['LETTER GRADE'])


alpha = 0.05
if p_value_fall_spring < alpha:
    print("fall21-22 and fall22_23 averages are significantly different.")
else:
    print("fall21-22 and fall22_23 averages are not significantly different.")

if p_value_fall_spring < alpha:
    print("spring21_22 and spring22_23 averages are significantly different.")
else:
    print("spring21_22 and spring22_23 averages are not significantly different.")


average_fall_total = (average_fall21_22 + average_fall22_23) / 2
average_spring_total = (average_spring21_22 + average_spring22_23) / 2

print('average_fall_total',average_fall_total)
print('average_spring_total', average_spring_total)